# Generated by Django 3.0.1 on 2021-08-23 10:40

from django.db import migrations, models
import shorten1000.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2048)),
                ('uuid', models.CharField(default=shorten1000.models.get_uuid, max_length=10, unique=True)),
            ],
            options={
                'db_table': 'URL',
            },
        ),
    ]
