# Generated by Django 3.0.1 on 2021-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten1000', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(max_length=2048),
        ),
    ]
